name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout only k8/deployment.yml from remote repo
        uses: actions/checkout@v4
        with:
          repository: http://github.com/ABC-GENERAL/BLAZEMETER
          ref: main
          sparse-checkout: |
            k8/deployment.yml
          path: remote

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: my-aks-rg
          cluster-name: my-aks-cluster

      - name: Deploy application
        run: kubectl apply -f kubernetes/deployment.yaml
